apiVersion: agent-install.openshift.io/v1beta1
kind: AgentServiceConfig
metadata:
  name: agent
  annotations:
    argocd.argoproj.io/sync-wave: "+10"
spec:
  databaseStorage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
  filesystemStorage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
  imageStorage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
  osImages:
    - cpuArchitecture: x86_64
      openshiftVersion: '4.18'
      rootFSUrl: 'http://192.168.1.159:8080/ocp/rhcos-4.18.30-x86_64-live-rootfs.x86_64.img'
      url: 'http://192.168.1.159:8080/ocp/rhcos-4.18.30-x86_64-live.x86_64.iso'
      version: 4.18.30
