apiVersion: v1
kind: ConfigMap
metadata:
  name: mirror-registry-config
  namespace: sno-ztp
data:
  registries.conf: |
    unqualified-search-registries = ["registry.redhat.io", "registry.access.redhat.com", "docker.io"]

    [[registry]]
      prefix = ""
      location = "quay.io/openshift-release-dev/ocp-release"
      [[registry.mirror]]
        location = "mirror-registry.pkar.tech:8443/ocp/openshift/release-images"
        pull-from-mirror = "digest-only"

    [[registry]]
      prefix = ""
      location = "quay.io/openshift-release-dev/ocp-v4.0-art-dev"
      [[registry.mirror]]
        location = "mirror-registry.pkar.tech:8443/ocp/openshift/release"
        pull-from-mirror = "digest-only"

    [[registry]]
      prefix = ""
      location = "registry.redhat.io"
      [[registry.mirror]]
        location = "mirror-registry.pkar.tech:8443/ocp"
        pull-from-mirror = "digest-only"

  ca-bundle.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDpzCCAo+gAwIBAgIUNszGcJJOsQTXjoMTzxNaDYb6XhMwDQYJKoZIhvcNAQEL
    BQAwczELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAlZBMREwDwYDVQQHDAhOZXcgWW9y
    azENMAsGA1UECgwEUXVheTERMA8GA1UECwwIRGl2aXNpb24xIjAgBgNVBAMMGW1p
    cnJvci1yZWdpc3RyeS5wa2FyLnRlY2gwHhcNMjYwMjA4MTQ0OTA3WhcNMjcwMTMw
    MTQ0OTA3WjAaMRgwFgYDVQQDDA9xdWF5LWVudGVycHJpc2UwggEiMA0GCSqGSIb3
    DQEBAQUAA4IBDwAwggEKAoIBAQDYfvSAnTlQiKKagJlV78KGH0QqJwLGDp3mOUqQ
    BU+I7oPLfMVFPklgPfJFYvFZvRvdsCK4cJ5Ng2fxGSRHSR9P5IFpnkKnfFBxVLP6
    0T4cCIYKzosp/TSjNITmMYa8bkYNChwESBkyooK3DWBjftsxyoBvcdB3+nvYh3Fq
    xsJ3J/4SqbnDtWnE+fiXY4kY4xtj5MD0KZbpOaq1SRfemGDDMJKpMy2gcnnOnW/5
    JQv2hbiu2J0grt5bEShMIVxQiHe3c7jf6HeA4vL9op8/u/843B8Y1ORkuWX0U/re
    5YYrsHNN/4iromHnjNMmTw2p8uH6xQ0Mtf1GFeiXeLqW4lI3AgMBAAGjgYswgYgw
    CwYDVR0PBAQDAgLkMBMGA1UdJQQMMAoGCCsGAQUFBwMBMCQGA1UdEQQdMBuCGW1p
    cnJvci1yZWdpc3RyeS5wa2FyLnRlY2gwHQYDVR0OBBYEFBg1blxQ9ZrvubC58zXL
    JMc63ayjMB8GA1UdIwQYMBaAFKHo/YD/HU55HdFnCjlzEicOJ0DDMA0GCSqGSIb3
    DQEBCwUAA4IBAQAE47SkcltrSSHC7S5CnXaxY6ciRQc6LNLn+jav0olkXrollOUM
    SNT1PbEFMSqSdpraBa8vsQ3RguVv5nD+0Pvg+VO1PFfeJIDk3/mlCc8d+/7PmUPo
    QI1C2CjNScJmHCvInb7nS2MRha9YrwnT2TYLOSE9U0DDKNbh54r6ynNf6R5LNA+U
    tsYEM52ngTohoBckz5Iv2ke6EEF5XOTF1okSKMycFWNa/IkcwSXP/9zSyOfTnu1g
    EhzoRiY66pQv5UWUflAPPAw4TDsTnyBURwqXj12JMy0ISr/HLtdjA8PzGjyfX83p
    5RHtzM7jFZ/+V95Yl6CPqibYUT/ko+WQsMOA
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIID8TCCAtmgAwIBAgIUIYHXjZ1lSfcXvKv8lp9Ht/IgOncwDQYJKoZIhvcNAQEL
    BQAwczELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAlZBMREwDwYDVQQHDAhOZXcgWW9y
    azENMAsGA1UECgwEUXVheTERMA8GA1UECwwIRGl2aXNpb24xIjAgBgNVBAMMGW1p
    cnJvci1yZWdpc3RyeS5wa2FyLnRlY2gwHhcNMjYwMjA4MTQ0OTA1WhcNMjgxMTI4
    MTQ0OTA1WjBzMQswCQYDVQQGEwJVUzELMAkGA1UECAwCVkExETAPBgNVBAcMCE5l
    dyBZb3JrMQ0wCwYDVQQKDARRdWF5MREwDwYDVQQLDAhEaXZpc2lvbjEiMCAGA1UE
    AwwZbWlycm9yLXJlZ2lzdHJ5LnBrYXIudGVjaDCCASIwDQYJKoZIhvcNAQEBBQAD
    ggEPADCCAQoCggEBAJ+Q/x20G+R3LD3SNF+uc3/tq4t74Fj5aN43ZNglrg4F4b+O
    ZSuhHb6trX1kzgDb2EkfLymPrGnFYch+oY4mX1QNueGMRusu4m/KZq6V9m+hJpVc
    +OBy4M2oH3uWEnwIasWcUx7YGsUJdiA/ySIvF/R3+nBW5eX1m/Gp7uPESgA5tGZh
    FMvOgWCa4tUTeoaalmltYpEnvdnlw9QZxKpAnbD1Uh7tyVUHD2rrHohciMCR+fzB
    IzHKD4LXFuaBM+/3sdNSjGbfX1ZPkuqpvFUcqKuV2Oa3SgdhWkrFTw/jG7TMTx62
    aPsKNXrgizkhQkShgY/FQoJDQcJGZOCwqrtFaf0CAwEAAaN9MHswCwYDVR0PBAQD
    AgLkMBMGA1UdJQQMMAoGCCsGAQUFBwMBMCQGA1UdEQQdMBuCGW1pcnJvci1yZWdp
    c3RyeS5wa2FyLnRlY2gwEgYDVR0TAQH/BAgwBgEB/wIBATAdBgNVHQ4EFgQUoej9
    gP8dTnkd0WcKOXMSJw4nQMMwDQYJKoZIhvcNAQELBQADggEBAHK2f4lsLnTVAm8D
    DYeChVMJ3g2/kgKR8IbopJn6jxlEmwrisGQQVCIzAIVKSns1VwL6thewEKaWhOFN
    wawRzMoa1b7Yrs+mwGVmCbmU2YSFlJi8N0SckRFA2DTWd/zB/k/rrLogKqdDC/pB
    D2Cm8ujfuDvFMcXvQQqCX68RnQ8HTK8b/AW1pxd4pXlutNMHspGUVdp2L6HF7ejI
    PQsufp4hrWgAa5hczvQM+RBng13qgu1luXiRlkZyZtine9HElqY+uE1A6GclB6nE
    B9CSp692e0ytNfhRcNXrKhgslc6KbJlmTUtcf2ei05H1ioVP06qTCYhMaApRWokZ
    +7hygP4=
    -----END CERTIFICATE-----
