apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  #- 00-namespace.yaml	
  - 01-bmc-secret.yaml
  #- 02-pull-secret.yaml
  - 03-mirror-registry-config.yaml
  - 04-clusterinstance.yaml 
  - 05-klusterlet-addon-config.yaml
  #- mir-reg-41830.yaml
  #- ibi-clusterinstance.yaml   

configMapGenerator:
  - files:
    #- extra-manifests/00-idms.yaml
    - extra-manifests/01-disable-operator.yaml
    - extra-manifests/02-redhat-operator-cs.yaml
    - extra-manifests/50-masters-chrony-configuration.yaml
    - extra-manifests/50-masters-containers-policy-configuration.yaml
    - extra-manifests/50-workers-chrony-configuration.yaml
    - extra-manifests/50-workers-containers-policy-configuration.yaml
    - extra-manifests/99-master-custom-timezone-configuration.yaml
    - extra-manifests/99-worker-custom-timezone-configuration.yaml    
    name: extra-manifests-cm
    namespace: sno-ztp

generatorOptions:
  disableNameSuffixHash: true
