apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  #- 00-namespace.yaml	
  - 01-bmc-secret.yaml
  #- 02-pull-secret.yaml
  #- 03-mirror-registry-config.yaml
  - mir-reg-41830.yaml
  #- 04-clusterinstance.yaml
  - ibi-clusterinstance.yaml  
  - 05-klusterlet-addon-config.yaml

configMapGenerator:
  - files:
    - extra-manifests/00-idms.yaml
    - extra-manifests/01-disable-operator.yaml
    - extra-manifests/02-redhat-operator-cs.yaml
    name: extra-manifests-cm
    namespace: sno-ztp

generatorOptions:
  disableNameSuffixHash: true
