apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../nfs
  - 00-ns-acm.yaml
  - 01-og-acm.yaml
  - 02-sub-acm.yaml
  - 04-mch-acm.yaml
  - 05-provisioning.yaml
  #- 06-cm-mirror-registry.yaml
  - 07-agent-service-config.yaml
