apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generators:
  #- policy-generator.yaml
  - policy-generator-hub.yaml  
  - policy-generator-sno.yaml  
resources:
  - 00-managed-clusterset.yaml
  - managedcluster-sno-ztp.yaml  
