apiVersion: v1
kind: ConfigMap
metadata:
  name: mirror-registry-config
  namespace: sno2-ztp
data:
  registries.conf: |
    unqualified-search-registries = ["registry.redhat.io", "registry.access.redhat.com", "docker.io"]

    [[registry]]
      prefix = ""
      location = "quay.io/openshift-release-dev/ocp-release"
      [[registry.mirror]]
        location = "mirror-registry2.pkar.tech:8443/ocp/openshift/release-images"

    [[registry]]
      prefix = ""
      location = "quay.io/openshift-release-dev/ocp-v4.0-art-dev"
      [[registry.mirror]]
        location = "mirror-registry2.pkar.tech:8443/ocp/openshift/release"

    [[registry]]
      prefix = ""
      location = "registry.redhat.io"
      [[registry.mirror]]
        location = "mirror-registry2.pkar.tech:8443/ocp"

  ca-bundle.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDiDCCAnCgAwIBAgIUOrkuB9vrMEVWdA+QD1dzaFuQnJEwDQYJKoZIhvcNAQEL
    BQAwZDELMAkGA1UEBhMCSU4xCzAJBgNVBAgMAldCMRAwDgYDVQQHDAdLb2xrYXRh
    MQ0wCwYDVQQKDARRdWF5MREwDwYDVQQLDAhEaXZpc2lvbjEUMBIGA1UEAwwLKi5w
    a2FyLnRlY2gwHhcNMjYwMjE3MDIxMTE0WhcNMzUxMTE3MDIxMTE0WjAaMRgwFgYD
    VQQDDA9xdWF5LWVudGVycHJpc2UwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
    AoIBAQCuvdxP/a6zCao+01EsWXV/4+DgK5hgFmog1+v5kMT5QBs19e/tzvZcVnKD
    FweTF4KFsILT5euaZRlt5X7z97oSVUYHJbeZpQReou1G/YU5GsfQWMxq8hoLh79k
    XUibh3g9CmgBEGpMytok4EF7ViA4OJWWqCfOTjvFJ9ZpNqiKMNhD1s3me6jPwHM0
    veZnaK/QM8EYGZwJBTOQ3vHHJB7aqrNoSmWN0f5gMxxMn5PNQQUNpNLLEQOTvvUo
    1ILnquaQEjbXqtPrtOgeCsBoxQ8fCv5r1153gLrIjFMwKMgKepisvwv8xUdRpgan
    TVU7eAZP5RIuKRAwODAixHlaF95PAgMBAAGjfDB6MAsGA1UdDwQEAwIC5DATBgNV
    HSUEDDAKBggrBgEFBQcDATAWBgNVHREEDzANggsqLnBrYXIudGVjaDAdBgNVHQ4E
    FgQUn4nOFASY//qDmKyLKNBUHbsDIYgwHwYDVR0jBBgwFoAUURPDCT62rSbORo36
    blwW7TeWBm0wDQYJKoZIhvcNAQELBQADggEBAI/V/EdP4ZBtUWChD/9H7+V8Z+w/
    KPK3AJ9K5org2Kjl6DwzWddVmUN2OqULmkUr3XoAkyiBLa1ARozfe0MZp5QFRPKz
    WVckqKN+TRpfH8GDi2dCRl7dwzsDea9lC+L65D/KdHUHyB1yyyaSYzbyGhj1fu6z
    kQ46ZtXA0zn9Y8OnI8ngZ5R7Sy48RCCKz8FL6eCD9PSZ47rFFUWA7SE3KSmeVwT2
    TWCKxwZnKu8c7qi9W5ESgm+nM1OrzlFB59MungdvLl6Ndj199m08lilN2elku+35
    zRSYGAFzNEcwEluyJlpaSVYMGx7MOLLlIpFFZPvGeqZ5Dter7FgbIIVkESs=
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIDxTCCAq2gAwIBAgIUDyWytUoKfIr5vNroagWfL6AvyoAwDQYJKoZIhvcNAQEL
    BQAwZDELMAkGA1UEBhMCSU4xCzAJBgNVBAgMAldCMRAwDgYDVQQHDAdLb2xrYXRh
    MQ0wCwYDVQQKDARRdWF5MREwDwYDVQQLDAhEaXZpc2lvbjEUMBIGA1UEAwwLKi5w
    a2FyLnRlY2gwHhcNMjYwMjE3MDIxMTE0WhcNMzYwMjE1MDIxMTE0WjBkMQswCQYD
    VQQGEwJJTjELMAkGA1UECAwCV0IxEDAOBgNVBAcMB0tvbGthdGExDTALBgNVBAoM
    BFF1YXkxETAPBgNVBAsMCERpdmlzaW9uMRQwEgYDVQQDDAsqLnBrYXIudGVjaDCC
    ASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALjxdDf480KiAMkTJrcVEyLI
    Dfdh26mrH2w9EoM0jIKt8UK+EI1wXqLvtC2qLYoTuSdDSIoawr7Cgw/AKJijhtr2
    4TOsvinvTuEIugSDHIDnt0cUIMaLDhTWVIhemGOq1Nu6gnaLGsNTgVullKZn4Dp0
    J8dQNeSc0wwiohhptO3/hYML96+oD8aBS1wR2sgSasSXYFn+Udqz7RgwGTYFwxm5
    205Ze8NAqUL43F0D5zEuSTyPMeHQLoXW6ghNt5llq3MMq7ZggISZKt+lRgpDJ8rn
    4J87b5vOSV66yLkP6VB1gXNF5+oaEdkjhGCI6xfrC8Nnu+HD1VQu7QZ7lPvcj/UC
    AwEAAaNvMG0wCwYDVR0PBAQDAgLkMBMGA1UdJQQMMAoGCCsGAQUFBwMBMBYGA1Ud
    EQQPMA2CCyoucGthci50ZWNoMBIGA1UdEwEB/wQIMAYBAf8CAQEwHQYDVR0OBBYE
    FFETwwk+tq0mzkaN+m5cFu03lgZtMA0GCSqGSIb3DQEBCwUAA4IBAQCV4bCjwB9Z
    KRREkJHn+YRqR0FfdqXE/rkTmcDjLWVGcTBkIjyfBhyLDaaX4bZON8mAq9+8CucK
    ve2NBpgVBhf3delcKDjOwtsv1ENLXhZZiqQuI2Ei3OK7O3qpESsVRgBqQFYuQgFV
    +EcovOqihX8LZZVqf9QHTIGKvF26X1wx75Nwd1nvKlSrM2ObKks7HNwd0suN/VVW
    Ay8qVLbWez3vF0U8Cc0cccYLDxGEmVlpNJP+qx9DPQN8IstMtRSfqCFN6qemHZqE
    iZGPSH2g5qH0E1Nzs4HH/o45BzFVR8EC3CpVbEALSYnjXD3+JicyLSD6NhMwjRh9
    lOfqBc1TN/Qk
    -----END CERTIFICATE-----
