apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generators:
- 05-policygenerator.yaml

resources:
- 00-managedclusterset.yaml
#- 00-sno-ztp-ns.yaml
#- 00-hcp-ztp-ns.yaml
- 01-managedclustersetbinding.yaml
#- 02-argocd-placement.yaml
